export const CREATE_CLASSROOM = "CREATE_CLASSROOM";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";
export const FETCH_CLASSROOMS = "FETCH_CLASSROOMS";
